blank_issues_enabled: false
contact_links:
  - name: Validot on StackOverflow
    url: https://stackoverflow.com/questions/tagged/validot
    about: 'Please ask and answer questions using the tag #validot'